Revert "Add Android.bp"
This reverts commit 331037aafb8d9b886076d78f699f1027b0e68520.

Reason for revert: Broken builds

"^out/soong/.intermediates/external/rust/crates/base64/base64_host_test_src_lib/linux_glibc_x86_64/base64_host_test_src_lib:" out/soong/.intermediates/external/rust/crates/base64/base64_host_test_src_lib/linux_glibc_x86_64/base64_host_test_src_lib.d.raw > out/soong/.intermediates/external/rust/crates/base64/base64_host_test_src_lib/linux_glibc_x86_64/base64_host_test_src_lib.d
error[E0432]: unresolved import `rand::FromEntropy`
   --> external/rust/crates/base64/src/chunked_encoder.rs:117:9
    |
117 |         FromEntropy, Rng,
    |         ^^^^^^^^^^^ no `FromEntropy` in the root

Change-Id: Idf87dabbb6b8030b37764b4745003a4797e8b578